require "core.options"
require "core.keymaps"
require "core.theme"
require "core.plugins"
require "core.comment"
require "module.nvim_notify"
require "module.nvim_tree"
require "module.indent_blankline"
require "module.telescope"
-- require "module.twilight"
require "module.treesitter"
require "module.lualine"
require "module.mason"
require "module.trouble"
require "module.gitsigns"
require "module.alpha"
require "module.bufferline"
require "lsp.init"